### ISSUE TITLE
Exclude folder .git

### ISSUE THREAD

**Issue by luciorosella** [nicklasfrahm/scp-action#9]

**Comment by nicklasfrahm** [comment]
Hi @luciorosella, would it work for your use case if I add an `exclude` option, that allows you to specify, which files and folders to ignore?

**Comment by luciorosella** [comment]
Yes, it would be perfect to have an exclude

**Comment by nicklasfrahm** [comment]
Hey @luciorosella, I thought long and hard about this, but I was not able to come up with a nice way of doing this. My suggestion would be to do this via a script in separate step, similar to:

```yaml
...
deploy:
  steps:
    ...
    - run: |
        cp dist /tmp/deploy
        rm -rf /tmp/deploy/.git
    ...
```

Otherwise, this task would need to copy things to a temporary directory, which I believe is out of scope.
